# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'user' do
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'BlocksKit'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'iCarousel'
    pod 'WMPageController'
    pod 'ZWLimitCounter',         '~> 0.0.4'
#      pod 'MWPhotoBrowser'
#      pod 'PYPhotoBrowser'
#    pod 'XLPhotoBrowser'
    pod 'TYPagerController'
    pod 'MLTransition'
    pod 'MJExtension'
    pod 'SDWebImage', '~> 4.2.2'
    pod 'SVProgressHUD'
    pod 'SDCycleScrollView'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'TTGTagCollectionView'
#    pod 'NIMKit', :path =>'../'
    pod 'Toast', '~> 3.0'
    pod 'M80AttributedLabel', '~> 1.6.3'
    pod 'TZImagePickerController', '~> 1.9.0'
    pod 'WechatOpenSDK'

#    pod 'NIMSDK_LITE'
  target 'userTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'userUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
